# Read the Docs configuration file for RMNLib
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - doxygen
    - graphviz
  commands:
    # 1) Install Python requirements for Sphinx & extensions
    - echo "Installing Python dependencies…"
    - python -m pip install -r docs/requirements.txt

    # 2) Generate Doxygen XML (Makefile's doxygen target)
    - echo "Generating Doxygen XML…"
    - make doxygen

    # 3) Build full HTML (Makefile's html target runs sphinx-build)
    - echo "Building Sphinx docs…"
    - make html

    # 4) Copy the output into RTD's expected dir
    - echo "Copying HTML to RTD output…"
    - mkdir -p "$READTHEDOCS_OUTPUT/html"
    - cp -R docs/_build/html/. "$READTHEDOCS_OUTPUT/html"
