name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build & Test (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            label: ubuntu-latest.x64
          - os: ubuntu-latest
            arch: arm64
            label: ubuntu-latest.arm64
          - os: macos-latest
            arch: x64
            label: macos-latest
          - os: windows-latest
            arch: x64
            label: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download stb_image.h for cross-platform image support
        run: |
          curl -o src/stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h

      # ARM64 builds via QEMU + Docker
      - name: Set up QEMU emulation
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64
      - name: Install QEMU binfmt handlers
        if: matrix.arch == 'arm64'
        run: docker run --rm --privileged tonistiigi/binfmt --install all
      - name: Build & test in ARM64 container
        if: matrix.arch == 'arm64'
        run: |
          docker run --rm --platform=linux/arm64 \
            -v ${{ github.workspace }}:/src -w /src ubuntu:22.04 bash -lc "\
              apt-get update && apt-get install -y curl clang make flex bison unzip libcurl4-openssl-dev libopenblas-dev liblapacke-dev && \
              curl -o src/stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h && \
              make clean && make all && make test && \
              cp build/lib/libRMNLib.a libRMN.a"

      # On Linux (x64)
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libopenblas-dev \
            liblapacke-dev

      # On macOS (x64)
      - name: Ensure BLAS/LAPACK on macOS
        if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
        run: |
          echo "Using Accelerate.framework for BLAS/LAPACK on macOS"

      - name: Build & test on Linux/macOS
        if: runner.os != 'Windows' && matrix.arch == 'x64'
        run: |
          make clean
          make all
          make test-asan
          cp build/lib/libRMNLib.a libRMN.a

      # Windows
      - name: Set up MSYS2 & MinGW (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-lapack
            make
            flex
            bison

      - name: Build & test on Windows (AddressSanitizer not supported)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          curl -o src/stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h
          make clean
          make CC=gcc \
               CFLAGS="-std=c99 -I. -Isrc -O3 -Wall -Wextra \
                       -Wno-sign-compare -Wno-unused-parameter \
                       -Wno-missing-field-initializers -DSTB_IMAGE_AVAILABLE" \
               LEX=flex YACC="bison -y"
          cp build/lib/libRMNLib.a libRMN.a

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libRMN-${{ matrix.label }}
          path: libRMN.a

      - name: Package public headers
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        run: |
          mkdir -p header-pkg/include
          cp src/*.h header-pkg/include/
          zip -j header-pkg/libRMN-headers.zip header-pkg/include/*.h

      - name: Upload headers artifact
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: libRMN-headers
          path: header-pkg/libRMN-headers.zip

  release:
    name: Package & Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy header bundle
        run: |
          mkdir -p packages
          cp artifacts/libRMN-headers/libRMN-headers.zip packages/

      - name: Package libraries into ZIPs
        run: |
          mkdir -p packages
          for osdir in artifacts/*; do
            lib="${osdir}/libRMN.a"
            if [ ! -f "$lib" ]; then
              echo "Skipping $osdir (no library to package)"
              continue
            fi
            os=$(basename "$osdir")
            platform=${os#libRMN-}
            zipfile="packages/libRMN-${platform}.zip"

            if [[ "$platform" == *"windows"* ]]; then
              pwsh -Command "Compress-Archive -Path '$lib' -DestinationPath '$zipfile'"
            else
              zip -j "$zipfile" "$lib"
            fi
          done

      - name: Create or update GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: packages/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}